# Generated by Django 6.0.2 on 2026-03-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_stockmetric_beta_stockmetric_current_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmetric',
            name='exchange',
            field=models.CharField(db_index=True, default='UNKNOWN', max_length=10),
        ),
        migrations.AlterField(
            model_name='stockmetric',
            name='market_cap',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockmetric',
            name='symbol',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
